apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wildflyservers.wildfly.org
spec:
  group: wildfly.org
  names:
    kind: WildFlyServer
    listKind: WildFlyServerList
    plural: wildflyservers
    singular: wildflyserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationImage:
              description: ApplicationImage is the name of the application image to
                be deployed
              type: string
            disableHTTPRoute:
              description: 'TODO: how to use this?'
              type: boolean
            env:
              description: Env contains environment variables for the containers running
                the WildFlyServer application
              items:
                type: object
              type: array
            envFrom:
              items:
                type: object
              type: array
            jbossHome:
              description: JBossHome defines place where jboss distribution is located
                at the docker image defined by ApplicationImage
              type: string
            serviceAccountName:
              type: string
            sessionAffinity:
              description: SessionAffinity defines if connections from the same client
                ip are passed to the same WildFlyServer instance/pod each time
              type: boolean
            size:
              format: int32
              type: integer
            standaloneConfigMap:
              properties:
                key:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
            storage:
              properties:
                emptyDir:
                  type: object
                volumeClaimTemplate:
                  type: object
              type: object
          required:
          - applicationImage
          - size
          type: object
        status:
          properties:
            hosts:
              items:
                type: string
              type: array
            pods:
              items:
                properties:
                  name:
                    type: string
                  podIP:
                    type: string
                  state:
                    description: Represent the state of the Pod, it's used especially
                      during scale down the expected values are represented by the
                      PodState* constants  Read-only.
                    type: string
                required:
                - name
                - podIP
                - state
                type: object
              type: array
            scalingdownPods:
              description: Represents the number of pods which are in scaledown process
                what particular pod is scaling down can be verified by PodStatus  Read-only.
              format: int32
              type: integer
          required:
          - scalingdownPods
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
